[2018-03-23 17:23:53,585][MainThread:140294133593920][task_id:backend.main][main.py:93][INFO][用户1079614505@qq.com登录成功！]
[2018-03-23 17:23:54,989][MainThread:140294133593920][task_id:backend.main][main.py:158][INFO][运行run_strace 脚本 python /home/king/KindFortressMachine/backend/run_strace.py /home/king/KindFortressMachine/temp_files/5bbe3607-46c7-40bb-b50e-3949ed49fc2a 2 3]
[2018-03-23 17:23:54,991][MainThread:140294133593920][task_id:backend.main][main.py:168][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-23 17:23:55,216][MainThread:140622658799424][task_id:__main__][run_strace.py:72][INFO][获取用户执行run_strace.py脚本的参数['/home/king/KindFortressMachine/backend/run_strace.py', '/home/king/KindFortressMachine/temp_files/5bbe3607-46c7-40bb-b50e-3949ed49fc2a', '2', '3']]
[2018-03-23 17:23:55,216][MainThread:140622658799424][task_id:__main__][run_strace.py:32][INFO][执行run_strace.py脚本参数为unique_mark:/home/king/KindFortressMachine/temp_files/5bbe3607-46c7-40bb-b50e-3949ed49fc2a, user_id:2, select_bind_host_id:3]
[2018-03-23 17:23:55,220][MainThread:140622658799424][task_id:__main__][run_strace.py:35][INFO][执行run_strce.py脚本的用户user:1079614505@qq.com, 选择的绑定主机对象:JacobCentos0:jacob]
[2018-03-23 17:23:55,220][MainThread:140622658799424][task_id:__main__][run_strace.py:36][INFO][用来监测1079614505@qq.com所选主机JacobCentos0:jacob的ssh活动的线程启动了！]
[2018-03-23 17:23:55,338][MainThread:140622658799424][task_id:__main__][run_strace.py:52][WARNING][本次要监测的ssh进程/home/king/KindFortressMachine/temp_files/5bbe3607-46c7-40bb-b50e-3949ed49fc2a没获取到！]
[2018-03-23 17:23:55,339][MainThread:140622658799424][task_id:__main__][run_strace.py:53][INFO][本次获取到的要监测的ssh进程号为:b'']
[2018-03-23 17:23:55,359][MainThread:140622658799424][task_id:__main__][run_strace.py:66][INFO][在/home/king/KindFortressMachine/log/audit_log/2018-03-23/strace_47.log生成监测进程-b''-的日志！]
[2018-03-23 17:41:31,964][MainThread:140294133593920][task_id:backend.main][main.py:177][INFO][临时文件/home/king/KindFortressMachine/temp_files/5bbe3607-46c7-40bb-b50e-3949ed49fc2a删除成功！]
[2018-03-23 17:41:33,713][MainThread:140294133593920][task_id:backend.main][main.py:158][INFO][运行run_strace 脚本 python /home/king/KindFortressMachine/backend/run_strace.py /home/king/KindFortressMachine/temp_files/19f9d074-509d-40a5-8997-754bcabb7e10 2 3]
[2018-03-23 17:41:33,718][MainThread:140294133593920][task_id:backend.main][main.py:168][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-23 17:41:33,973][MainThread:140298676819776][task_id:__main__][run_strace.py:72][INFO][获取用户执行run_strace.py脚本的参数['/home/king/KindFortressMachine/backend/run_strace.py', '/home/king/KindFortressMachine/temp_files/19f9d074-509d-40a5-8997-754bcabb7e10', '2', '3']]
[2018-03-23 17:41:33,973][MainThread:140298676819776][task_id:__main__][run_strace.py:32][INFO][执行run_strace.py脚本参数为unique_mark:/home/king/KindFortressMachine/temp_files/19f9d074-509d-40a5-8997-754bcabb7e10, user_id:2, select_bind_host_id:3]
[2018-03-23 17:41:33,978][MainThread:140298676819776][task_id:__main__][run_strace.py:35][INFO][执行run_strce.py脚本的用户user:1079614505@qq.com, 选择的绑定主机对象:JacobCentos0:jacob]
[2018-03-23 17:41:33,978][MainThread:140298676819776][task_id:__main__][run_strace.py:36][INFO][用来监测1079614505@qq.com所选主机JacobCentos0:jacob的ssh活动的线程启动了！]
[2018-03-23 17:41:34,114][MainThread:140298676819776][task_id:__main__][run_strace.py:52][WARNING][本次要监测的ssh进程/home/king/KindFortressMachine/temp_files/19f9d074-509d-40a5-8997-754bcabb7e10没获取到！]
[2018-03-23 17:41:34,114][MainThread:140298676819776][task_id:__main__][run_strace.py:53][INFO][本次获取到的要监测的ssh进程号为:b'']
[2018-03-23 17:41:34,132][MainThread:140298676819776][task_id:__main__][run_strace.py:66][INFO][在/home/king/KindFortressMachine/log/audit_log/2018-03-23/strace_48.log生成监测进程-b''-的日志！]
[2018-03-23 17:41:49,923][MainThread:140499335980864][task_id:backend.main][main.py:93][INFO][用户1079614505@qq.com登录成功！]
[2018-03-23 17:44:14,617][MainThread:140535208904512][task_id:backend.main][main.py:95][INFO][用户1079614505@qq.com登录成功！]
[2018-03-23 17:44:16,277][MainThread:140535208904512][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-23 17:47:28,854][Thread-7:140688957818624][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /audit_log/49/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 100, in audit_log_detail
    audit_log_parser = audit.AuditLogHandler(audit_log_detail_path, condition_dict.get("parse_mark"))
  File "/home/king/KindFortressMachine/backend/audit.py", line 11, in __init__
    self.log_file_obj = AuditLogHandler._get_file(log_file)
  File "/home/king/KindFortressMachine/backend/audit.py", line 16, in _get_file
    return open(log_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/king/KindFortressMachine/log/audit_log/2018-03-23/strace_49.log'
[2018-03-23 17:47:29,161][Thread-8:140688957818624][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2018-03-23 17:47:31,756][Thread-9:140688957818624][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /audit_log/48/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 100, in audit_log_detail
    audit_log_parser = audit.AuditLogHandler(audit_log_detail_path, condition_dict.get("parse_mark"))
  File "/home/king/KindFortressMachine/backend/audit.py", line 11, in __init__
    self.log_file_obj = AuditLogHandler._get_file(log_file)
  File "/home/king/KindFortressMachine/backend/audit.py", line 16, in _get_file
    return open(log_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/king/KindFortressMachine/log/audit_log/2018-03-23/strace_48.log'
[2018-03-23 17:47:33,558][Thread-10:140688957818624][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /audit_log/47/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 100, in audit_log_detail
    audit_log_parser = audit.AuditLogHandler(audit_log_detail_path, condition_dict.get("parse_mark"))
  File "/home/king/KindFortressMachine/backend/audit.py", line 11, in __init__
    self.log_file_obj = AuditLogHandler._get_file(log_file)
  File "/home/king/KindFortressMachine/backend/audit.py", line 16, in _get_file
    return open(log_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/king/KindFortressMachine/log/audit_log/2018-03-23/strace_47.log'
[2018-03-23 17:47:35,475][Thread-11:140688957818624][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /audit_log/46/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 100, in audit_log_detail
    audit_log_parser = audit.AuditLogHandler(audit_log_detail_path, condition_dict.get("parse_mark"))
  File "/home/king/KindFortressMachine/backend/audit.py", line 11, in __init__
    self.log_file_obj = AuditLogHandler._get_file(log_file)
  File "/home/king/KindFortressMachine/backend/audit.py", line 16, in _get_file
    return open(log_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/king/KindFortressMachine/log/audit_log/2018-03-23/strace_46.log'
[2018-03-23 18:11:05,952][MainThread:140535208904512][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/9b5e4357-98c2-439b-aaf5-90a693ba9931删除成功！]
[2018-03-23 18:11:07,515][MainThread:140535208904512][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-23 18:11:13,638][MainThread:140535208904512][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/6be995dc-a377-4354-8da0-df4f3f7eef12删除成功！]
[2018-03-23 18:12:13,139][Thread-59:140688957818624][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /audit_log/46/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 100, in audit_log_detail
    audit_log_parser = audit.AuditLogHandler(audit_log_detail_path, condition_dict.get("parse_mark"))
  File "/home/king/KindFortressMachine/backend/audit.py", line 11, in __init__
    self.log_file_obj = AuditLogHandler._get_file(log_file)
  File "/home/king/KindFortressMachine/backend/audit.py", line 16, in _get_file
    return open(log_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/king/KindFortressMachine/log/audit_log/2018-03-23/strace_46.log'
[2018-03-23 18:12:30,449][MainThread:140535208904512][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-23 18:12:34,498][MainThread:140535208904512][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/ca943a77-60ca-4bdd-a4a4-1efb68c24251删除成功！]
[2018-03-23 18:12:56,999][MainThread:139712822859584][task_id:backend.main][main.py:95][INFO][用户1079614505@qq.com登录成功！]
[2018-03-23 18:12:58,851][MainThread:139712822859584][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-23 18:13:58,044][MainThread:139712822859584][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/c78e9ced-08ea-404b-bd4e-530e888ff4f1删除成功！]
[2018-03-23 18:13:59,532][MainThread:139712822859584][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-23 18:18:02,503][MainThread:139712822859584][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/1fc1170f-1785-4252-9347-6379adf0ac13删除成功！]
[2018-03-23 18:18:04,135][MainThread:139712822859584][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-23 18:18:08,431][MainThread:139712822859584][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/c9d00634-9eaa-4ff9-ab39-d29e6a5ff9e6删除成功！]
[2018-03-23 18:18:22,528][MainThread:140535208904512][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-23 18:18:30,004][MainThread:140535208904512][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/830c0fd8-3809-4ff6-b532-76b467343d47删除成功！]
[2018-03-23 18:19:00,857][MainThread:139738423088960][task_id:backend.main][main.py:95][INFO][用户1079614505@qq.com登录成功！]
[2018-03-23 18:19:02,668][MainThread:139738423088960][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-23 18:19:11,287][MainThread:139738423088960][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/19368268-e26c-443e-820d-97853e2d9d8d删除成功！]
[2018-03-23 18:19:22,109][Thread-81:140688957818624][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /audit_log/55/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 100, in audit_log_detail
    audit_log_parser = audit.AuditLogHandler(audit_log_detail_path, condition_dict.get("parse_mark"))
  File "/home/king/KindFortressMachine/backend/audit.py", line 11, in __init__
    self.log_file_obj = AuditLogHandler._get_file(log_file)
  File "/home/king/KindFortressMachine/backend/audit.py", line 16, in _get_file
    return open(log_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/king/KindFortressMachine/log/audit_log/2018-03-23/strace_55.log'
[2018-03-23 18:19:38,895][Thread-89:140688957818624][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /audit_log/54/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 100, in audit_log_detail
    audit_log_parser = audit.AuditLogHandler(audit_log_detail_path, condition_dict.get("parse_mark"))
  File "/home/king/KindFortressMachine/backend/audit.py", line 11, in __init__
    self.log_file_obj = AuditLogHandler._get_file(log_file)
  File "/home/king/KindFortressMachine/backend/audit.py", line 16, in _get_file
    return open(log_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/king/KindFortressMachine/log/audit_log/2018-03-23/strace_54.log'
[2018-03-23 18:19:41,500][Thread-90:140688957818624][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /audit_log/53/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 100, in audit_log_detail
    audit_log_parser = audit.AuditLogHandler(audit_log_detail_path, condition_dict.get("parse_mark"))
  File "/home/king/KindFortressMachine/backend/audit.py", line 11, in __init__
    self.log_file_obj = AuditLogHandler._get_file(log_file)
  File "/home/king/KindFortressMachine/backend/audit.py", line 16, in _get_file
    return open(log_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/king/KindFortressMachine/log/audit_log/2018-03-23/strace_53.log'
[2018-03-23 18:19:43,646][Thread-91:140688957818624][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /audit_log/52/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 100, in audit_log_detail
    audit_log_parser = audit.AuditLogHandler(audit_log_detail_path, condition_dict.get("parse_mark"))
  File "/home/king/KindFortressMachine/backend/audit.py", line 11, in __init__
    self.log_file_obj = AuditLogHandler._get_file(log_file)
  File "/home/king/KindFortressMachine/backend/audit.py", line 16, in _get_file
    return open(log_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/king/KindFortressMachine/log/audit_log/2018-03-23/strace_52.log'
[2018-03-24 15:21:35,347][MainThread:140045405288256][task_id:backend.main][main.py:95][INFO][用户1079614505@qq.com登录成功！]
[2018-03-24 15:21:37,051][MainThread:140045405288256][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-24 15:22:00,044][MainThread:140045405288256][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/e433dd91-d934-4c4b-aff0-e9bae5f1f8ef删除成功！]
[2018-03-24 15:22:01,325][MainThread:140045405288256][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-24 15:22:22,813][MainThread:140045405288256][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/087eb8a5-90c5-45f7-b773-d3f4abb7d1ee删除成功！]
[2018-03-24 15:22:24,636][MainThread:140045405288256][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-24 15:22:57,160][MainThread:140045405288256][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/2d251284-5fe9-4016-b83d-6c636573b4b9删除成功！]
[2018-03-24 15:23:14,121][MainThread:140576293418816][task_id:backend.main][main.py:95][INFO][用户1079614505@qq.com登录成功！]
[2018-03-24 15:23:15,636][MainThread:140576293418816][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-24 15:23:22,410][MainThread:140576293418816][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/aa7fca16-be28-432f-92e2-1d1bfaa5aa0f删除成功！]
[2018-03-24 15:23:32,264][MainThread:140576293418816][task_id:backend.main][main.py:184][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-24 15:24:40,777][MainThread:140576293418816][task_id:backend.main][main.py:193][INFO][临时文件/home/king/KindFortressMachine/temp_files/220d22a9-dbf2-45aa-8127-090d5d3e478c删除成功！]
[2018-03-24 15:26:04,860][Thread-84:139849484908288][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /audit_log/53/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 100, in audit_log_detail
    audit_log_parser = audit.AuditLogHandler(audit_log_detail_path, condition_dict.get("parse_mark"))
  File "/home/king/KindFortressMachine/backend/audit.py", line 11, in __init__
    self.log_file_obj = AuditLogHandler._get_file(log_file)
  File "/home/king/KindFortressMachine/backend/audit.py", line 16, in _get_file
    return open(log_file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/king/KindFortressMachine/log/audit_log/2018-03-23/strace_53.log'
[2018-03-24 15:26:05,271][Thread-85:139849484908288][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2018-03-25 10:39:29,986][Thread-9:11852][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /web_ssh/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 116, in web_ssh
    "web_ssh_url": settings.WEB_SSH_URL,
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\conf\__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'WEB_SSH_URL'
[2018-03-25 10:39:30,374][Thread-10:15328][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2018-03-25 10:39:54,818][Thread-1:2848][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /web_ssh/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 116, in web_ssh
    "web_ssh_url": settings.WEB_SSH_URL,
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\conf\__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'WEB_SSH_URL'
[2018-03-25 10:39:55,700][Thread-3:8036][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /web_ssh/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 116, in web_ssh
    "web_ssh_url": settings.WEB_SSH_URL,
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\conf\__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'WEB_SSH_URL'
[2018-03-25 10:52:39,282][Thread-10:6196][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /multitask_cmd/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view web.views.multitask_cmd didn't return an HttpResponse object. It returned None instead.
[2018-03-25 13:43:41,471][Thread-86:13792][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /multitask_cmd/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 126, in multitask_cmd
    return render(request, "multitask_cmd.html")
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\defaulttags.py", line 172, in render
    values = list(values)
TypeError: 'ManyRelatedManager' object is not iterable
[2018-03-25 15:31:25,025][Thread-4:788][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /multitask/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 145, in multitask
    ret["data"] = {"multi_task_obj_id": multi_task_obj.id}
AttributeError: 'NoneType' object has no attribute 'id'
[2018-03-25 15:57:31,965][Thread-8:15640][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /multitask/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 145, in multitask
    ret["data"] = {"multi_task_obj_id": multi_task_obj.id}
AttributeError: 'NoneType' object has no attribute 'id'
[2018-03-25 15:58:02,765][Thread-4:7392][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /multitask/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 142, in multitask
    if multi_task_handler_obj.is_vaild():  # 验证批量任务是否符合规范
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\backend\multi_task_handler.py", line 26, in is_vaild
    multiTaskType_clean = getattr(self, f"{multiTaskType}_clean")
AttributeError: 'MultiTaskHandler' object has no attribute 'dmd_clean'
[2018-03-25 16:05:06,758][Thread-4:2644][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /multitask/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 145, in multitask
    ret["data"] = {"multi_task_obj_id": multi_task_obj.id}
AttributeError: 'NoneType' object has no attribute 'id'
[2018-03-25 16:26:54,420][Thread-4:9384][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /multitask/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 145, in multitask
    ret["data"] = {"multi_task_obj_id": multi_task_obj.id}
AttributeError: 'NoneType' object has no attribute 'id'
[2018-03-25 16:30:24,378][Thread-8:15852][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /multitask/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 143, in multitask
    multi_task_obj = multi_task_handler_obj.run()  # 运行批量任务
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\backend\multi_task_handler.py", line 99, in run
    multi_task_func()
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\backend\multi_task_handler.py", line 79, in cmd
    result="init"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 554, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\fields\related_descriptors.py", line 216, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "'3'": "MultiTaskDetail.bind_host" must be a "BindHost" instance.
[2018-03-25 16:43:24,219][Thread-1:2996][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /admin/web/multitaskdetail/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\response.py", line 107, in render
    self.content = self.rendered_content
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 207, in render
    return self._render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 990, in render
    bit = node.render_annotated(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\base.py", line 957, in render_annotated
    return self.render(context)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\template\library.py", line 225, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 340, in result_list
    'results': list(results(cl))}
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 316, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 307, in __init__
    super(ResultList, self).__init__(*items)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 250, in items_for_result
    if force_text(result_repr) == '':
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\utils\encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\db\models\base.py", line 589, in __repr__
    u = six.text_type(self)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\models.py", line 179, in __str__
    return f"{self.get_task_type_display}-{self.content}"
RecursionError: maximum recursion depth exceeded while calling a Python object
[2018-03-25 17:27:25,085][Thread-1:3616][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:27:25,354][Thread-1:3616][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:27:56,165][Thread-1:3380][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:27:56,274][Thread-1:3380][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:28:34,107][Thread-1:7340][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:28:34,216][Thread-1:7340][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:30:18,886][Thread-1:11976][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:30:18,993][Thread-1:11976][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:30:58,337][Thread-1:10568][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:30:58,448][Thread-1:10568][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:31:45,335][Thread-1:11976][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:31:45,453][Thread-1:11976][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:32:35,665][Thread-1:4400][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:32:35,773][Thread-1:4400][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:39:32,238][Thread-1:1200][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:39:32,349][Thread-1:1200][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:44:45,025][Thread-4:988][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /multitask/]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 159, in multitask
    return HttpResponse(json.dumps(ret))
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'BindHost' is not JSON serializable
[2018-03-25 17:44:46,119][Thread-1:1228][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:44:46,219][Thread-1:1228][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:46:03,317][Thread-1:2908][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:46:03,426][Thread-1:2908][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:51:30,300][Thread-1:1420][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:51:30,412][Thread-1:1420][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:52:22,060][Thread-1:2676][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:52:22,171][Thread-1:2676][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:55:11,229][Thread-1:10396][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:55:11,333][Thread-1:10396][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 17:55:53,988][Thread-1:1400][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 17:55:54,124][Thread-1:1400][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:00:05,841][Thread-1:14804][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:00:05,948][Thread-1:14804][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:00:19,102][Thread-1:3080][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:00:19,207][Thread-1:3080][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:01:31,930][Thread-1:8968][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:01:32,058][Thread-1:8968][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:02:15,692][Thread-1:10608][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:02:15,799][Thread-1:10608][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:02:55,243][Thread-1:8928][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:02:55,358][Thread-1:8928][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:17:13,945][Thread-1:8592][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:17:14,053][Thread-1:8592][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:26:15,019][Thread-15:680][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2018-03-25 18:28:30,811][Thread-1:16180][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:28:31,125][Thread-1:16180][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:30:37,056][Thread-1:13164][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:30:37,172][Thread-1:13164][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:33:49,196][Thread-1:13752][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:33:49,309][Thread-1:13752][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:35:01,371][Thread-1:11072][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:35:01,477][Thread-1:11072][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:37:51,135][Thread-1:1468][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:37:51,241][Thread-1:1468][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:38:32,756][Thread-1:15408][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:38:32,862][Thread-1:15408][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:39:03,633][Thread-1:15960][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:39:03,739][Thread-1:15960][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:39:30,774][Thread-1:12868][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:39:30,881][Thread-1:12868][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:39:49,067][Thread-1:15408][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:39:49,183][Thread-1:15408][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:40:35,226][Thread-1:12904][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:40:35,332][Thread-1:12904][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:40:51,683][Thread-1:6704][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:40:51,789][Thread-1:6704][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:41:14,142][Thread-1:14356][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:41:14,253][Thread-1:14356][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:41:43,117][Thread-1:16100][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:41:43,225][Thread-1:16100][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:42:15,250][Thread-1:14468][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:42:15,357][Thread-1:14468][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:42:47,688][Thread-1:7072][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:42:47,793][Thread-1:7072][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:43:30,198][Thread-1:7800][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:43:30,300][Thread-1:7800][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:45:32,286][Thread-1:7396][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:45:32,396][Thread-1:7396][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:46:45,511][Thread-1:11076][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:46:45,617][Thread-1:11076][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:50:31,416][Thread-1:13856][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:50:31,528][Thread-1:13856][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:51:19,826][Thread-1:8116][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:51:19,940][Thread-1:8116][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:52:55,031][Thread-1:4932][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:52:55,141][Thread-1:4932][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:56:46,577][Thread-1:1472][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:56:46,684][Thread-1:1472][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:57:22,309][Thread-1:1140][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:57:22,414][Thread-1:1140][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:58:17,115][Thread-1:12556][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:58:17,224][Thread-1:12556][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 18:58:43,572][Thread-1:2752][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 18:58:43,687][Thread-1:2752][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:00:06,138][Thread-1:3296][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:00:06,241][Thread-1:3296][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:00:40,482][Thread-1:8792][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:00:40,589][Thread-1:8792][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:00:45,459][Thread-1:8548][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:00:45,568][Thread-1:8548][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:00:49,559][Thread-1:15076][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:00:49,669][Thread-1:15076][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:00:53,011][Thread-1:5204][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:00:53,115][Thread-1:5204][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:01:02,181][Thread-1:16336][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:01:02,286][Thread-1:16336][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:01:20,764][Thread-1:8792][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:01:20,869][Thread-1:8792][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:01:51,302][Thread-1:2520][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:01:51,411][Thread-1:2520][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:03:29,205][Thread-1:2480][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:03:29,330][Thread-1:2480][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:03:34,873][Thread-1:4420][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:03:34,979][Thread-1:4420][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:39:28,940][Thread-1:6752][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:39:29,054][Thread-1:6752][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:41:49,578][Thread-1:5612][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:41:49,698][Thread-1:5612][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:42:12,670][Thread-1:9452][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:42:12,776][Thread-1:9452][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:42:32,308][Thread-1:8448][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:42:32,419][Thread-1:8448][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 19:43:10,325][Thread-1:5916][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 19:43:10,434][Thread-1:5916][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 20:10:44,248][Thread-1:7252][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 20:10:44,377][Thread-1:7252][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 20:12:20,545][Thread-1:9072][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 20:12:20,658][Thread-1:9072][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 20:12:43,828][Thread-1:15728][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 20:12:43,933][Thread-1:15728][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 20:14:31,910][Thread-1:11244][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 20:14:32,032][Thread-1:11244][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 20:14:42,310][Thread-1:13952][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 20:14:42,415][Thread-1:13952][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 20:15:04,005][Thread-1:2756][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 20:15:04,116][Thread-1:2756][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 20:37:15,633][Thread-1:1676][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 20:37:15,741][Thread-1:1676][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 20:38:11,172][Thread-1:9308][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 20:38:11,279][Thread-1:9308][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 21:08:19,104][MainThread:139632423569216][task_id:backend.main][main.py:59][INFO][用户1079614505@qq.com登录成功！]
[2018-03-25 21:08:20,451][MainThread:139632423569216][task_id:backend.main][main.py:148][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-25 21:08:23,675][MainThread:139632423569216][task_id:backend.main][main.py:157][INFO][临时文件/home/king/KindFortressMachine/temp_files/1545e0be-6c6c-491f-b65f-0f30d83780ea删除成功！]
[2018-03-25 21:08:39,866][MainThread:139632423569216][task_id:backend.main][main.py:148][INFO][用户1079614505@qq.com连接了192.168.125.180,
                                使用远程账户jacob]
[2018-03-25 21:09:43,454][MainThread:139632423569216][task_id:backend.main][main.py:157][INFO][临时文件/home/king/KindFortressMachine/temp_files/264da87d-793c-4233-9379-4788853d11c3删除成功！]
[2018-03-25 21:10:38,332][Thread-1:140253938177792][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 21:10:39,028][Thread-1:140253938177792][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 21:10:48,512][Thread-1:140219751986944][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 21:10:48,795][Thread-1:140219751986944][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 21:12:28,162][Thread-1:140322218673920][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 21:12:28,301][Thread-1:140322218673920][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 21:12:40,262][Thread-1:140102316295936][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 21:12:40,389][Thread-1:140102316295936][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 21:12:51,448][Thread-1:139862958941952][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 21:12:51,541][Thread-1:139862958941952][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 21:13:02,165][Thread-1:140594547230464][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 21:13:02,261][Thread-1:140594547230464][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 21:13:13,997][Thread-1:140693281826560][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 21:13:14,093][Thread-1:140693281826560][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 21:15:41,885][Thread-1:139948955993856][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_7.4)]
[2018-03-25 21:15:41,983][Thread-1:139948955993856][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-25 21:16:20,945][Thread-338:140665337931520][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2018-03-26 09:42:32,101][Thread-49:5008][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2018-03-26 09:47:01,514][Thread-1:12896][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 09:47:01,677][Thread-1:12896][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:00:16,753][Thread-1:9052][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:00:16,860][Thread-1:9052][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:24:55,330][Thread-1:1168][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:24:55,468][Thread-1:1168][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:30:51,003][Thread-1:4280][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:30:51,116][Thread-1:4280][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:35:28,147][Thread-1:15876][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:35:28,261][Thread-1:15876][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:41:47,066][Thread-1:139785374742272][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:41:47,389][Thread-1:139785374742272][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:42:27,968][Thread-1:139813901293312][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:42:28,090][Thread-1:139813901293312][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:42:50,276][Thread-1:140118753838848][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:42:50,380][Thread-1:140118753838848][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:45:42,968][Thread-1:139682834376448][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:45:43,076][Thread-1:139682834376448][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:45:48,591][Thread-1:140283991000832][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:45:48,696][Thread-1:140283991000832][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:45:53,829][Thread-1:140303470491392][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:45:53,935][Thread-1:140303470491392][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:48:43,204][Thread-1:139809632962304][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:48:43,310][Thread-1:139809632962304][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:49:24,957][Thread-1:140146785208064][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:49:25,061][Thread-1:140146785208064][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:52:22,893][Thread-1:140335456388864][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:52:22,999][Thread-1:140335456388864][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:52:38,383][Thread-1:139648482199296][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:52:38,486][Thread-1:139648482199296][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:53:36,436][Thread-1:140236034324224][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:53:36,542][Thread-1:140236034324224][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:53:49,231][Thread-1:140555358000896][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:53:49,336][Thread-1:140555358000896][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:54:04,650][Thread-1:140007291369216][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:54:04,754][Thread-1:140007291369216][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 10:56:25,740][Thread-1:140060754958080][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 10:56:25,845][Thread-1:140060754958080][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 11:00:51,191][Thread-1:139882894477056][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 11:00:51,296][Thread-1:139882894477056][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 11:03:41,247][Thread-3:140641374893824][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 148, in multitask
    multi_task_run_status, multi_task_obj = multi_task_handler_obj.run()  # 运行批量任务
  File "/home/king/KindFortressMachine/backend/multi_task_handler.py", line 94, in run
    multi_task_func()
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/king/KindFortressMachine/backend/multi_task_handler.py", line 80, in cmd
    subprocess.run(f"kill {multi_task_pid}")
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'kill 3833': 'kill 3833'
[2018-03-26 11:03:43,854][Thread-1:139875889084160][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 11:03:43,960][Thread-1:139875889084160][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 11:52:46,511][Thread-1:139871169480448][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 11:52:46,630][Thread-1:139871169480448][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 11:54:09,266][Thread-1:139886063355648][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 11:54:09,372][Thread-1:139886063355648][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 11:54:24,367][Thread-61:140381467436800][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 152, in multitask
    for multi_task_detail_obj in multi_task_obj.multitaskdetail_set.all():
AttributeError: 'NoneType' object has no attribute 'multitaskdetail_set'
[2018-03-26 11:58:06,431][Thread-1:139872388220672][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 11:58:06,535][Thread-1:139872388220672][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 11:58:16,296][Thread-1:139837594158848][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 11:58:16,400][Thread-1:139837594158848][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 11:59:22,252][Thread-1:140491101816576][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 11:59:22,356][Thread-1:140491101816576][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 11:59:36,915][Thread-1:140219769198336][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 11:59:37,018][Thread-1:140219769198336][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:00:20,451][Thread-1:140645304653568][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:00:20,556][Thread-1:140645304653568][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:04:35,139][Thread-1:140659817559808][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:04:35,241][Thread-1:140659817559808][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:04:43,745][Thread-1:140625710688000][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:04:43,848][Thread-1:140625710688000][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:04:58,732][Thread-1:140549774616320][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:04:58,837][Thread-1:140549774616320][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:06:22,241][Thread-1:140673335908096][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:06:22,343][Thread-1:140673335908096][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:06:49,188][Thread-1:139870913632000][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:06:49,292][Thread-1:139870913632000][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:07:02,786][Thread-1:139828795225856][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:07:02,892][Thread-1:139828795225856][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:07:06,090][Thread-1:139966185666304][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:07:06,197][Thread-1:139966185666304][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:07:08,905][Thread-1:139627566872320][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:07:09,007][Thread-1:139627566872320][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:07:11,194][Thread-1:140059884992256][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:07:11,298][Thread-1:140059884992256][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:07:15,905][Thread-1:139991663847168][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:07:16,009][Thread-1:139991663847168][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:07:19,877][Thread-1:140609821579008][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:07:19,989][Thread-1:140609821579008][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:07:23,544][Thread-1:140438786627328][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:07:23,646][Thread-1:140438786627328][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:07:26,332][Thread-1:139942129506048][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:07:26,438][Thread-1:139942129506048][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:07:29,163][Thread-1:139953121203968][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:07:29,268][Thread-1:139953121203968][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:07:31,138][Thread-1:140051713959680][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:07:31,243][Thread-1:140051713959680][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:07:32,682][Thread-1:140717012797184][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:07:32,788][Thread-1:140717012797184][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:07:59,790][Thread-1:140103395915520][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:07:59,893][Thread-1:140103395915520][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:09:33,502][Thread-1:140619214747392][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:09:33,612][Thread-1:140619214747392][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:11:12,918][Thread-1:139763754620672][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:11:13,023][Thread-1:139763754620672][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:20:59,885][Thread-210:139868807788288][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/anaconda3/envs/py3-dj/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/king/KindFortressMachine/web/views.py", line 152, in multitask
    for multi_task_detail_obj in multi_task_obj.multitaskdetail_set.all():
AttributeError: 'NoneType' object has no attribute 'multitaskdetail_set'
[2018-03-26 12:31:06,105][Thread-1:140540336629504][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:31:06,209][Thread-1:140540336629504][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:40:12,682][Thread-1:139635292133120][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:40:12,788][Thread-1:139635292133120][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 12:53:24,180][Thread-1:139950341244672][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 12:53:24,283][Thread-1:139950341244672][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:14:38,504][Thread-1:140077574137600][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:14:38,608][Thread-1:140077574137600][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:15:44,534][Thread-1:139752555489024][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:15:44,639][Thread-1:139752555489024][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:16:09,615][Thread-1:140308671452928][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:16:09,718][Thread-1:140308671452928][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:19:03,791][Thread-1:140404158899968][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:19:03,896][Thread-1:140404158899968][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:19:19,663][Thread-1:140496566273792][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:19:19,766][Thread-1:140496566273792][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:20:04,104][Thread-1:139913983391488][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:20:04,209][Thread-1:139913983391488][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:20:19,748][Thread-1:140700969084672][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:20:19,851][Thread-1:140700969084672][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:21:26,434][Thread-1:139990080186112][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:21:26,536][Thread-1:139990080186112][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:25:20,729][Thread-198:140556109727488][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2018-03-26 14:41:06,441][Thread-1:16972][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:41:06,634][Thread-1:16972][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:51:45,687][Thread-1:3060][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:51:45,802][Thread-1:3060][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:54:05,723][Thread-1:1624][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:54:05,833][Thread-1:1624][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:54:20,189][Thread-1:15284][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:54:20,308][Thread-1:15284][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 14:54:35,180][Thread-1:15284][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 14:54:35,301][Thread-1:15284][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 15:05:18,121][Thread-232:14136][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:11:08,149][Thread-256:17276][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:11:56,393][Thread-276:7788][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:15:56,046][Thread-298:14320][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:17:33,675][Thread-302:5904][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:17:52,666][Thread-305:14140][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:19:15,094][Thread-308:11104][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:20:07,025][Thread-328:7868][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:22:21,584][Thread-329:13628][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:23:09,240][Thread-335:16444][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:26:10,477][Thread-355:17080][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:26:21,971][Thread-358:7448][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:27:05,116][Thread-359:5236][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:41:13,964][Thread-381:13708][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:41:15,856][Thread-382:4248][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:41:17,649][Thread-383:11936][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:42:32,312][Thread-384:9408][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:42:37,484][Thread-385:6908][task_id:django.request][base.py:152][WARNING][Not Found: /student/upload_homework/]
[2018-03-26 15:45:26,998][Thread-4:13684][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/upload_file]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view web.views.multitask_upload_file didn't return an HttpResponse object. It returned None instead.
[2018-03-26 15:53:35,166][Thread-23:9388][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/upload_file]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 196, in multitask_upload_file
    user_multi_task_file_transfer_dir = os.path.join(settings.MULTI_TASK_FILE_TRANSFER_DIR, request.user.id)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\ntpath.py", line 114, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'int'
[2018-03-26 15:53:53,493][Thread-1:12612][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/upload_file]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 197, in multitask_upload_file
    os.removedirs(user_multi_task_file_transfer_dir)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\os.py", line 238, in removedirs
    rmdir(name)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'D:\\Nutstore_Files\\PythonStudy\\day27\\KindFortressMachine\\multi_task_file_transfer\\2'
[2018-03-26 15:55:40,981][Thread-4:8796][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/upload_file]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view web.views.multitask_upload_file didn't return an HttpResponse object. It returned None instead.
[2018-03-26 15:58:08,887][Thread-5:17260][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/upload_file]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 199, in multitask_upload_file
    os.removedirs(user_multi_task_file_transfer_dir)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\os.py", line 238, in removedirs
    rmdir(name)
OSError: [WinError 145] 目录不是空的。: 'D:\\Nutstore_Files\\PythonStudy\\day27\\KindFortressMachine\\multi_task_file_transfer\\2'
[2018-03-26 15:58:37,877][Thread-4:14384][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/upload_file]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 199, in multitask_upload_file
    os.remove(user_multi_task_file_transfer_dir)
PermissionError: [WinError 5] 拒绝访问。: 'D:\\Nutstore_Files\\PythonStudy\\day27\\KindFortressMachine\\multi_task_file_transfer\\2'
[2018-03-26 16:00:25,074][Thread-1:12184][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/upload_file]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 199, in multitask_upload_file
    os.rmdir(user_multi_task_file_transfer_dir)
OSError: [WinError 145] 目录不是空的。: 'D:\\Nutstore_Files\\PythonStudy\\day27\\KindFortressMachine\\multi_task_file_transfer\\2'
[2018-03-26 16:03:46,279][Thread-4:18048][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/upload_file]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Nutstore_Files\PythonStudy\day27\KindFortressMachine\web\views.py", line 197, in multitask_upload_file
    if request.META.has_key('HTTP_X_FORWARDED_FOR'):
AttributeError: 'dict' object has no attribute 'has_key'
[2018-03-26 16:05:31,586][Thread-3:16888][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/upload_file]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view web.views.multitask_upload_file didn't return an HttpResponse object. It returned None instead.
[2018-03-26 16:06:56,157][Thread-4:17428][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/upload_file]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view web.views.multitask_upload_file didn't return an HttpResponse object. It returned None instead.
[2018-03-26 16:07:02,778][Thread-5:17552][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /api/multitask/upload_file]
Traceback (most recent call last):
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\lingx\AppData\Local\conda\conda\envs\py3-dj\lib\site-packages\django\core\handlers\base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view web.views.multitask_upload_file didn't return an HttpResponse object. It returned None instead.
[2018-03-26 16:36:06,435][Thread-1:14380][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 16:36:06,596][Thread-1:14380][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 16:38:11,868][Thread-1:16996][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 16:38:11,978][Thread-1:16996][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 16:38:12,327][MainThread:18332][task_id:paramiko.transport.sftp][sftp.py:131][INFO][[chan 0] Opened sftp connection (server version 3)]
[2018-03-26 16:40:10,115][Thread-1:14560][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 16:40:10,224][Thread-1:14560][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 16:40:10,512][MainThread:2868][task_id:paramiko.transport.sftp][sftp.py:131][INFO][[chan 0] Opened sftp connection (server version 3)]
[2018-03-26 16:47:38,967][Thread-1:9376][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 16:47:39,080][Thread-1:9376][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 16:47:39,401][MainThread:13048][task_id:paramiko.transport.sftp][sftp.py:131][INFO][[chan 0] Opened sftp connection (server version 3)]
[2018-03-26 16:48:55,712][Thread-1:17592][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 16:48:55,830][Thread-1:17592][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 16:48:56,141][MainThread:15652][task_id:paramiko.transport.sftp][sftp.py:131][INFO][[chan 0] Opened sftp connection (server version 3)]
[2018-03-26 16:55:01,970][Thread-1:8048][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 16:55:02,080][Thread-1:8048][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 16:55:02,376][MainThread:18404][task_id:paramiko.transport.sftp][sftp.py:131][INFO][[chan 0] Opened sftp connection (server version 3)]
[2018-03-26 16:57:17,589][Thread-1:16628][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 16:57:17,708][Thread-1:16628][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 16:57:18,022][MainThread:12728][task_id:paramiko.transport.sftp][sftp.py:131][INFO][[chan 0] Opened sftp connection (server version 3)]
[2018-03-26 17:05:24,384][Thread-1:7028][task_id:paramiko.transport][transport.py:1687][INFO][Connected (version 2.0, client OpenSSH_6.6.1)]
[2018-03-26 17:05:24,527][Thread-1:7028][task_id:paramiko.transport][transport.py:1687][INFO][Authentication (password) successful!]
[2018-03-26 17:05:24,858][MainThread:18268][task_id:paramiko.transport.sftp][sftp.py:131][INFO][[chan 0] Opened sftp connection (server version 3)]
